### ISSUE TITLE
Table Import Export Integration Tests failing in bacee1a

### ISSUE THREAD

**Issue by aboy021** [sethreno/schemazen#206]
Some of the integration tests are failing in bacee1a768df0991995518954c10bd3250ffdef8 when I run them locally:

Test.Integration.TableTest:

- TestImportAndExportNonDefaultSchema
- TestExportData
- TestImportAndExportDateTimeWithoutLosePrecision
- TestImportAndExportIgnoringComputedData

They all fail with the error "Incorrect number of columns".

I haven't been able to work out the cause at this stage. 
I've been having some other issues to do with column defaults which I'll detail in a different issue.

Here's a dump of the failed tests:

```
TableTest (4 tests) [0:20.067] Aborted: Exit code is -1 (Not available): 3 tests failed
 TestExportData [0:03.672] Aborted: Exit code is -1 (Not available)
 TestImportAndExportDateTimeWithoutLosePrecision [0:03.190] Failed: SchemaZen.Library.Models.DataFileException: Incorrect number of columns - in file named C:\Users\arthur.boyer\AppData\Local\Temp\tmp25BB.tmp:1
SchemaZen.Library.Models.DataFileException
Incorrect number of columns - in file named C:\Users\arthur.boyer\AppData\Local\Temp\tmp25BB.tmp:1
   at SchemaZen.Library.Models.Table.ImportData(String conn, String filename) in C:\Source\schemazen\Library\Models\Table.cs:line 255
   at Test.Integration.TableTest.TestImportAndExportDateTimeWithoutLosePrecision() in C:\Source\schemazen\Test\Integration\TableTest.cs:line 115
   at Test.Integration.TableTest.TestImportAndExportDateTimeWithoutLosePrecision() in C:\Source\schemazen\Test\Integration\TableTest.cs:line 121
   at Xunit.DependencyInjection.DependencyInjectionTestInvoker.AsyncStack(Task task, Activity activity)


 TestImportAndExportIgnoringComputedData [0:03.163] Failed: SchemaZen.Library.Models.DataFileException: Incorrect number of columns - in file named C:\Users\arthur.boyer\AppData\Local\Temp\tmpF283.tmp:1
SchemaZen.Library.Models.DataFileException
Incorrect number of columns - in file named C:\Users\arthur.boyer\AppData\Local\Temp\tmpF283.tmp:1
   at SchemaZen.Library.Models.Table.ImportData(String conn, String filename) in C:\Source\schemazen\Library\Models\Table.cs:line 255
   at Test.Integration.TableTest.TestImportAndExportIgnoringComputedData() in C:\Source\schemazen\Test\Integration\TableTest.cs:line 82
   at Test.Integration.TableTest.TestImportAndExportIgnoringComputedData() in C:\Source\schemazen\Test\Integration\TableTest.cs:line 88
   at Xunit.DependencyInjection.DependencyInjectionTestInvoker.AsyncStack(Task task, Activity activity)


 TestImportAndExportNonDefaultSchema [0:03.276] Failed: SchemaZen.Library.Models.DataFileException: Incorrect number of columns - in file named C:\Users\arthur.boyer\AppData\Local\Temp\tmpE61E.tmp:1
SchemaZen.Library.Models.DataFileException
Incorrect number of columns - in file named C:\Users\arthur.boyer\AppData\Local\Temp\tmpE61E.tmp:1
   at SchemaZen.Library.Models.Table.ImportData(String conn, String filename) in C:\Source\schemazen\Library\Models\Table.cs:line 255
   at Test.Integration.TableTest.TestImportAndExportNonDefaultSchema() in C:\Source\schemazen\Test\Integration\TableTest.cs:line 151
   at Test.Integration.TableTest.TestImportAndExportNonDefaultSchema() in C:\Source\schemazen\Test\Integration\TableTest.cs:line 157
   at Xunit.DependencyInjection.DependencyInjectionTestInvoker.AsyncStack(Task task, Activity activity)
```

**Comment by aboy021** [comment]
As the source has moved ahead significantly I think this is a distraction and won't be fixed.
