### ISSUE TITLE
Characters in object name causes failure in file naming

### ISSUE THREAD

**Issue by coenier** [sethreno/schemazen#32]
If database object contains a character that is not supported by file system like "?" replace it with something else? Currently the export breaks with an error see below

```error
Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at model.Database.ScriptToDir(String tableHint)
   at console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at console.Program.Main(String[] args)
```

**Comment by keith-hall** [comment]
I have made a fix to replace invalid characters with a dash ("-") character.  However, it could potentially be possible that filenames will no longer be unique once they have been altered, and we may run into some edge cases where some objects could seem to not get scripted because the files are being overwritten straightaway...  This will require a bit more work / refactoring to fix if it becomes an issue, simply because the MakeFileName routine doesn't know anything about the folder in which the file is to be created, making it impossible to add a unique numeric suffix to the end of the filename for example.

**Comment by coenier** [comment]
Great stuff, perhaps the object ID could be used when the replace occurs to prevent the this.

**Comment by keith-hall** [comment]
That is an excellent idea @coenier :+1:

**Comment by keith-hall** [comment]
Doh, currently we are not retrieving or storing object_id from the database, so that will also be a fair amount of work I imagine... I wonder how often we will hit this problem?

**Comment by coenier** [comment]
I was surprise to find the character "?" in the object name in first place. I think what you have know is good for now.

**Comment by keith-hall** [comment]
Cool, I think we will raise a separate issue for it if it ever becomes a problem then :) thanks @coenier
