### ISSUE TITLE
SQL data type geography is not supported

### ISSUE THREAD

**Issue by acraibray** [sethreno/schemazen#71]
I was recieving the error, "SQL data type geography is not supported" when running schemazen against one of my databases running on SQL Server 2012, v11.0.2100.60.  I tried adding a case for the "geography" datatype in column.cs and I was able to complete the export successfully.  Based on the recent commit, linked below, some test coverage should also be added but this could be an easy addition.  I'm leaving the actual fix for posterity as I am currently at work and can't spend anymore time on this.

https://github.com/sethreno/schemazen/commit/a294ecb8fa087ec0d92e5209a838c658e093a1b3?diff=split

![2016-02-17 10 51 32](https://cloud.githubusercontent.com/assets/7356422/13115113/812a0038-d564-11e5-8368-790b4b5600a5.png)

**Comment by ertejaspatel** [comment]
I have similar issue and I am using geography and geometry columns. What change did you make in order to generate script successfully.
Any help would be appreciated.
Thanks

**Comment by sethreno** [comment]
This is fixed in 1.3.38

**Comment by sdurrance** [comment]
This error is returned on a Geometry field:
SQL data type geometry is not supported.
   at SchemaZen.model.Column.ScriptBase(Boolean includeDefaultConstraint)
   at SchemaZen.model.ColumnList.Script()
   at SchemaZen.model.Table.ScriptCreate()
   at SchemaZen.model.Database.WriteScriptDir(String name, ICollection`1 objects, Action`2 log)
   at SchemaZen.model.Database.ScriptToDir(String tableHint, Action`2 log)
   at SchemaZen.console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at SchemaZen.console.Program.Main(String[] args)
