### ISSUE TITLE
Specified cast is not valid

### ISSUE THREAD

**Issue by ertejaspatel** [sethreno/schemazen#84]
at SchemaZen.model.Database.LoadColumnsBase(IDataReader dr, List`1 tables)
   at SchemaZen.model.Database.LoadColumns(SqlCommand cm)
   at SchemaZen.model.Database.Load()
   at SchemaZen.console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at SchemaZen.console.Program.Main(String[] args)

**Comment by sethreno** [comment]
I'm not able to reproduce this. Please provide a script of the object(s) that I can use to reproduce.

**Comment by sethreno** [comment]
Closing as I'm not able to reproduce.
