### ISSUE TITLE
Unable to cast object of type 'System.DBNull' to type 'System.String'

### ISSUE THREAD

**Issue by ertejaspatel** [sethreno/schemazen#85]
Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at SchemaZen.model.Database.LoadColumnDefaults(SqlCommand cm)
   at SchemaZen.model.Database.Load()
   at SchemaZen.console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at SchemaZen.console.Program.Main(String[] args)

**Comment by ertejaspatel** [comment]
I found similar error occur in following methods in Database.cs:
        LoadColumnDefaults(cm);
        LoadColumnComputes(cm);
        LoadCheckConstraints(cm);

**Comment by sethreno** [comment]
I'm not able to reproduce this. Please provide a script of the object(s) that I can use to reproduce.

**Comment by sethreno** [comment]
closing as I'm not able to reproduce
